In [1]:
## mode chioce
## fist Swiss data mode coice 
## At the end of this file MonteCarlo procees for Chicago can be found


#import packages

import pandas as pd
import biogeme.database as db
import biogeme.biogeme as bio
from biogeme import models

In [2]:
##this part is adopted from Biogeme database
# data preparation
path = "F:/CIVIL 583/Project/Codes/3step/swissmetro.dat"
pandas = pd.read_table(path)
pandas

GROUP  SURVEY  SP    ID  PURPOSE  FIRST  TICKET  WHO  LUGGAGE  AGE  \
0          2       0   1     1        1      0       1    1        0    3   
1          2       0   1     1        1      0       1    1        0    3   
2          2       0   1     1        1      0       1    1        0    3   
3          2       0   1     1        1      0       1    1        0    3   
4          2       0   1     1        1      0       1    1        0    3   
...      ...     ...  ..   ...      ...    ...     ...  ...      ...  ...   
10723      3       1   1  1192        4      1       7    1        0    5   
10724      3       1   1  1192        4      1       7    1        0    5   
10725      3       1   1  1192        4      1       7    1        0    5   
10726      3       1   1  1192        4      1       7    1        0    5   
10727      3       1   1  1192        4      1       7    1        0    5   

       ...  TRAIN_TT  TRAIN_CO  TRAIN_HE  SM_TT  SM_CO  SM_HE  SM_SEATS  \
0      ...       112        48       120     63     52     20         0   
1      ...       103        48        30     60     49     10         0   
2      ...       130        48        60     67     58     30         0   
3      ...       103        40        30     63     52     20         0   
4      ...       130        36        60     63     42     20         0   
...    ...       ...       ...       ...    ...    ...    ...       ...   
10723  ...       148        13        30     93     17     30         0   
10724  ...       148        12        30     96     16     10         0   
10725  ...       148        16        60     93     16     20         0   
10726  ...       178        16        30     96     17     30         0   
10727  ...       148        13        60     96     21     30         0   

       CAR_TT  CAR_CO  CHOICE  
0         117      65       2  
1         117      84       2  
2         117      52       2  
3          72      52       2  
4          90      84       2  
...       ...     ...     ...  
10723     156      56       2  
10724      96      70       3  
10725      96      56       3  
10726      96      91       2  
10727     120      70       3  

[10728 rows x 28 columns]

In [3]:
pandas.describe()

GROUP        SURVEY       SP            ID       PURPOSE  \
count  10728.000000  10728.000000  10728.0  10728.000000  10728.000000   
mean       2.630034      0.630034      1.0    596.500000      2.914430   
std        0.482818      0.482818      0.0    344.116678      1.147443   
min        2.000000      0.000000      1.0      1.000000      1.000000   
25%        2.000000      0.000000      1.0    298.750000      2.000000   
50%        3.000000      1.000000      1.0    596.500000      3.000000   
75%        3.000000      1.000000      1.0    894.250000      3.250000   
max        3.000000      1.000000      1.0   1192.000000      9.000000   

              FIRST        TICKET           WHO       LUGGAGE           AGE  \
count  10728.000000  10728.000000  10728.000000  10728.000000  10728.000000   
mean       0.470638      2.888423      1.493289      0.678691      2.898490   
std        0.499160      2.191100      0.708293      0.603388      1.031726   
min        0.000000      1.000000      0.000000      0.000000      1.000000   
25%        0.000000      1.000000      1.000000      0.000000      2.000000   
50%        0.000000      3.000000      1.000000      1.000000      3.000000   
75%        1.000000      3.000000      2.000000      1.000000      4.000000   
max        1.000000     10.000000      3.000000      3.000000      6.000000   

       ...      TRAIN_TT      TRAIN_CO      TRAIN_HE         SM_TT  \
count  ...  10728.000000  10728.000000  10728.000000  10728.000000   
mean   ...    166.626025    514.335477     70.100671     87.466350   
std    ...     77.353284   1088.931881     37.431633     53.550371   
min    ...     31.000000      4.000000     30.000000      8.000000   
25%    ...    109.000000     58.000000     30.000000     55.000000   
50%    ...    157.000000     94.000000     60.000000     78.000000   
75%    ...    209.000000    170.000000    120.000000    109.000000   
max    ...   1049.000000   5040.000000    120.000000    796.000000   

              SM_CO         SM_HE      SM_SEATS        CAR_TT        CAR_CO  \
count  10728.000000  10728.000000  10728.000000  10728.000000  10728.000000   
mean     670.340697     20.020507      0.118568    123.795209     78.742077   
std     1441.594614      8.161895      0.323295     88.710743     55.263663   
min        6.000000     10.000000      0.000000      0.000000      0.000000   
25%       70.000000     10.000000      0.000000     70.000000     40.000000   
50%      111.000000     20.000000      0.000000    120.000000     76.000000   
75%      209.000000     30.000000      0.000000    176.000000    112.000000   
max     6720.000000     30.000000      1.000000   1560.000000    520.000000   

             CHOICE  
count  10728.000000  
mean       2.152778  
std        0.632293  
min        0.000000  
25%        2.000000  
50%        2.000000  
75%        3.000000  
max        3.000000  

[8 rows x 28 columns]

In [4]:
database = db.Database(path, pandas)

In [5]:
from biogeme.expressions import Beta, DefineVariable

##from headers import *
globals().update(database.variables)

##Replace also any occurence of bioLogLogit by biogeme.models.loglogit.

In [6]:
##removing some observations

database.getSampleSize()

10728

In [7]:
exclude = ((PURPOSE != 1) * ( PURPOSE != 3)  + (CHOICE == 0)) > 0
database.remove(exclude)

In [8]:
database.getSampleSize()

6768

In [9]:
#type(pandas )

In [10]:
#pandas.to_csv(r'F:/CIVIL 583/Project/Codes/3step/swissmetro.CSV', index = False)

In [11]:
## Parameters estimation
##(starting value. lower band , upper band, 0:estimate for each   1:keep this value fixed or reference level)
ASC_CAR = Beta('ASC_CAR', 0 , None, None, 0)
ASC_TRAIN = Beta('ASC_TRAIN', 0 , None, None, 0)
ASC_SM = Beta('ASC_SM', 0 , None, None, 1)
B_TIME = Beta('B_TIME', 0 , None, None, 0)
B_COST = Beta('B_COST', 0 , None, None, 0)

In [12]:
## new variables definition
# add new column to database

CAR_AV_SP = DefineVariable('CAR_AV_SP', CAR_AV  * (SP != 0),database)
TRAIN_AV_SP = DefineVariable('TRAIN_AV_SP', TRAIN_AV  * (SP != 0),database)
TRAIN_TT_SCALED = DefineVariable('TRAIN_TT_SCALED', TRAIN_TT / 100.00 ,database)
TRAIN_COST_SCALED = DefineVariable('TRAIN_COST_SCALED', TRAIN_CO / 100.00 ,database)
SM_TT_SCALED = DefineVariable('SM_TT_SCALED', SM_TT/ 100.00 ,database)
SM_COST_SCALED = DefineVariable('SM_COST_SCALED', SM_CO/ 100.00 ,database)
CAR_TT_SCALED = DefineVariable('CAR_TT_SCALED', CAR_TT/ 100.00 ,database)
CAR_COST_SCALED = DefineVariable('CAR_COST_SCALED', CAR_CO/ 100.00 ,database)

In [13]:
## Utility functions Specification
# train:1, CAR = 3,SWISSMETRO = 2 
v1 = ASC_TRAIN + B_TIME * TRAIN_TT_SCALED + B_COST * TRAIN_COST_SCALED
v2 = ASC_SM + B_TIME * SM_TT_SCALED + B_COST * SM_COST_SCALED
v3 = ASC_CAR + B_TIME * CAR_TT_SCALED + B_COST * CAR_COST_SCALED

#Utility of alternatives
v = {1: v1, 2:v2, 3:v3}
#Aavailability of altenatives
av = {1: TRAIN_AV_SP, 2:SM_AV, 3: CAR_AV_SP }

In [14]:
##loglikelihood function
#(utility, availability, choice set)
logprob = models.loglogit(v,av,CHOICE)

In [15]:
biogeme = bio.BIOGEME(database,logprob)
biogeme.modelName = "01logit"
#the name will be used to create output file

In [16]:
results = biogeme.estimate()

In [17]:
pandasResults = results.getEstimatedParameters()
pandasResults

Value   Std err     t-test   p-value  Rob. Std err  Rob. t-test  \
ASC_CAR    0.073462  0.042146   1.743044  0.081326      0.059306     1.238706   
ASC_TRAIN -0.609323  0.054569 -11.166148  0.000000      0.080045    -7.612283   
B_COST     0.006345  0.002620   2.421593  0.015453      0.002206     2.875948   
B_TIME    -1.156287  0.054234 -21.320266  0.000000      0.095915   -12.055289   

           Rob. p-value  
ASC_CAR    2.154542e-01  
ASC_TRAIN  2.686740e-14  
B_COST     4.028164e-03  
B_TIME     0.000000e+00

In [18]:
print(results)


Results for model [01logit]
Output file (HTML):			01logit~00.html
Nbr of parameters:		4
Sample size:			6768
Excluded data:			3960
Init log likelihood:		-6964.663
Final log likelihood:		-5590.464
Likelihood ratio test:		2748.398
Rho square:			0.197
Rho bar square:			0.197
Akaike Information Criterion:	11188.93
Bayesian Information Criterion:	11216.21
Final gradient norm:		3.747134e-05
ASC_CAR        : 0.0735[0.0421 1.74 0.0813][0.0593 1.24 0.215]
ASC_TRAIN      : -0.609[0.0546 -11.2 0][0.08 -7.61 2.69e-14]
B_COST         : 0.00635[0.00262 2.42 0.0155][0.00221 2.88 0.00403]
B_TIME         : -1.16[0.0542 -21.3 0][0.0959 -12.1 0]
('ASC_TRAIN', 'ASC_CAR'):	0.0014	0.607	-15.4	0	0.00388	0.818	-14.7	0
('B_COST', 'ASC_CAR'):	3.12e-05	0.283	-1.62	0.106	4.96e-05	0.379	-1.15	0.251
('B_COST', 'ASC_TRAIN'):	2.29e-05	0.16	11.4	0	3.67e-05	0.208	7.73	1.04e-14
('B_TIME', 'ASC_CAR'):	-0.0015	-0.655	-14	0	-0.00478	-0.839	-8.24	2.22e-16
('B_TIME', 'ASC_TRAIN'):	-0.00216	-0.729	-5.41	6.4e-08	-0.00682	-0.88

In [25]:
results.getHtml()

"<html><head><script src='http://transp-or.epfl.ch/biogeme/sorttable.js'></script><meta http-equiv='Content-Type' content='text/html; charset=utf-8' /><title>01logit - Report from biogeme 3.2.5 [2020-04-07]</title><meta name='keywords' content='biogeme, discrete choice, random utility'><meta name='description' content='Report from biogeme 3.2.5 [2020-04-07]'><meta name='author' content='Michel Bierlaire'><style type=text/css>.biostyle\t{font-size:10.0pt;\tfont-weight:400;\tfont-style:normal;\tfont-family:Courier;}.boundstyle\t{font-size:10.0pt;\tfont-weight:400;\tfont-style:normal;\tfont-family:Courier;        color:red}</style></head><body bgcolor='#ffffff'><p>biogeme 3.2.5 [2020-04-07]</p>\n<p><a href='https://www.python.org/' target='_blank'>Python</a> package</p>\n<p>Home page: <a href='http://biogeme.epfl.ch' target='_blank'>http://biogeme.epfl.ch</a></p>\n<p>Submit questions to <a href='https://groups.google.com/d/forum/biogeme' target='_blank'>https://groups.google.com/d/forum/b

In [29]:
###trips are imprted from second step to be divided into mode share table
import numpy as np
trips = np.load('C:/Users/User/Desktop/583-chicago/2step/TripDistribution.npy')



In [31]:
trips.shape

(11, 11)

In [64]:
###Monte Carlo to divide Chicago trip distribution table 
import random
transit = np.zeros(trips.shape)
sov= np.zeros(trips.shape)
hov = np.zeros(trips.shape)
sov_range= 0.746
hov_range = 0.746 + 0.118
transit_range = 0.746 + 0.118 + 0.135

i = 0
j = 0
count = 0
for i in range(len(trips)):
    for j in range(len(trips)):
        count = 0
        while count < trips[i,j]:
            rand = random.uniform(0,1)
            if rand < sov_range:
                sov[i,j] += 1
            elif rand < hov_range:
                hov[i,j] += 1
            elif rand < transit_range:
                transit[i,j] += 1
            else:
                continue
        
            count += 1
    

In [65]:
rand

0.23212501279770592

In [66]:
hov

array([[1.938133e+06, 4.294300e+04, 4.000000e+00, 2.800000e+02,
        4.000000e+00, 1.023000e+03, 7.000000e+00, 2.200000e+02,
        3.500000e+01, 0.000000e+00, 1.250000e+02],
       [4.751000e+03, 3.105380e+05, 3.000000e+01, 2.814500e+04,
        3.300000e+01, 9.690000e+02, 4.800000e+01, 5.570000e+02,
        2.000000e+00, 1.000000e+00, 0.000000e+00],
       [2.400000e+01, 1.882000e+03, 1.002600e+04, 2.000000e+02,
        1.042500e+04, 1.000000e+00, 0.000000e+00, 3.123000e+03,
        0.000000e+00, 0.000000e+00, 0.000000e+00],
       [9.700000e+01, 7.199500e+04, 4.000000e+00, 5.865900e+04,
        1.410000e+02, 7.950000e+02, 4.691100e+04, 1.000000e+01,
        0.000000e+00, 0.000000e+00, 0.000000e+00],
       [5.800000e+01, 4.737000e+03, 2.042700e+04, 4.817000e+03,
        7.667000e+03, 2.000000e+00, 1.000000e+00, 2.944000e+03,
        0.000000e+00, 0.000000e+00, 0.000000e+00],
       [2.000000e+00, 3.300000e+01, 0.000000e+00, 1.100000e+01,
        0.000000e+00, 2.484720e+05, 8.400

In [57]:
sov

array([[34.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [59]:
transit

array([[6., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
sov= np.zeros(trips.shape)
sov[0,0] += 1

In [42]:
sov

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])